# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_sn_fast <- function(x) {
    .Call(`_fastqnsn_C_sn_fast`, x)
}

C_sn_int_fast <- function(x) {
    .Call(`_fastqnsn_C_sn_int_fast`, x)
}

C_qn_fast <- function(x) {
    .Call(`_fastqnsn_C_qn_fast`, x)
}

C_qn_int_fast <- function(x) {
    .Call(`_fastqnsn_C_qn_int_fast`, x)
}
